#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments # (error catching)

#------------------------------------------------------------------------------

wmake $targetType baramPODbuildROM
wmake $targetType baramPODreconstruct

#------------------------------------------------------------------------------
